# Generated by Django 3.0.5 on 2021-06-08 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210607_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-id',), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
