# Generated by Django 3.0.5 on 2021-06-04 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_title_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='genres',
            new_name='genre',
        ),
    ]
